### ISSUE TITLE
[testnet4] assertion failed: value.is_sign_positive()

### ISSUE THREAD

**Issue by BrandyJSon** [comit-network/xmr-btc-swap#1691]
**Describe the bug**
Trying to do a testnet swap with my self using a self hosted electrum testnet4 server results in an error on the Bob end of the transaction. From assertion failed: value.is_sign_postiive(). It would appear to be an error in estimating fees based on the backtrace. Additionally I have tried but mempool.space's electrum server for testnet4 as well as my own with it as a peer. Neither fixed the problem.

**Lost/trapped Funds**
No

**Debug logs**
## Full rust backtrace of error
```dev@oak:~$ RUST_BACKTRACE=full ./swap --testnet -j buy-xmr --monero-daemon-address http://127.0.0.1:38083 --seller /ip4/192.168.122.27/tcp/9939/p2p/12D3KooWQA4fXDYLNXgxPsVZmnR8kh2wwHUQnkH9e1Wjc8KyJ7p8 --change-address tb1qpflmvpnh687wp568d7d3msyn7axpfzg6sud8rh --receive-address 7BqpcZsDq9m1eQfAgy3jGL3z5rVstdro4TX8tB1tgavi9c1XAnvQuFxG7hLanVMSHJXfM6hekmcUuDL4pcKJu55gCEhUiWH --electrum-rpc tcp://127.0.0.1:50001
{"fields":{"message":"Logging initialized to /home/dev/.local/share/xmr-btc-swap/cli/testnet/logs"}}
{"fields":{"message":"Connected to Alice","peer_id":"/ip4/192.168.122.27/tcp/9939/p2p/12D3KooWQA4fXDYLNXgxPsVZmnR8kh2wwHUQnkH9e1Wjc8KyJ7p8"},"span":{"method_name":"BuyXmr","swap_id":"f00c84dd-c40b-4aa2-8173-6e6c9bb402b2","name":"method"},"spans":[{"method_name":"BuyXmr","swap_id":"f00c84dd-c40b-4aa2-8173-6e6c9bb402b2","name":"method"}]}
{"fields":{"message":"Received quote","price":"0.002698 BTC","minimum_amount":"0.0001 BTC","maximum_amount":"0.02 BTC"},"span":{"method_name":"BuyXmr","swap_id":"f00c84dd-c40b-4aa2-8173-6e6c9bb402b2","name":"method"},"spans":[{"method_name":"BuyXmr","swap_id":"f00c84dd-c40b-4aa2-8173-6e6c9bb402b2","name":"method"}]}
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bdk-0.28.0/src/types.rs:61:9:
assertion failed: value.is_sign_positive()
stack backtrace:
   0:     0x5749bdb394cc - std::backtrace_rs::backtrace::libunwind::trace::ha69d38c49f1bf263
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5749bdb394cc - std::backtrace_rs::backtrace::trace_unsynchronized::h93125d0b85fd543c
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5749bdb394cc - std::sys_common::backtrace::_print_fmt::h8d65f438e8343444
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5749bdb394cc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41751d2af6c8033a
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5749bdb6968c - core::fmt::rt::Argument::fmt::h5db2f552d8a28f63
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/rt.rs:138:9
   5:     0x5749bdb6968c - core::fmt::write::h99465148a27e4883
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/mod.rs:1114:21
   6:     0x5749bdb34f6e - std::io::Write::write_fmt::hee8dfd57bd179ab2
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/io/mod.rs:1763:15
   7:     0x5749bdb392b4 - std::sys_common::backtrace::_print::h019a3cee3e814da4
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5749bdb392b4 - std::sys_common::backtrace::print::h55694121c2ddf918
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5749bdb3aac3 - std::panicking::default_hook::{{closure}}::h29cbe3da3891b0b0
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:272:22
  10:     0x5749bdb3a7e4 - std::panicking::default_hook::h881e76b2b8c74280
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:292:9
  11:     0x5749bdb3b045 - std::panicking::rust_panic_with_hook::hcc36e25b6e33969c
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:731:13
  12:     0x5749bdb3aef6 - std::panicking::begin_panic_handler::{{closure}}::ha415efb0f69f41f9
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:601:13
  13:     0x5749bdb399f6 - std::sys_common::backtrace::__rust_end_short_backtrace::h395fe90f99451e4e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x5749bdb3ac92 - rust_begin_unwind
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
  15:     0x5749bc81b505 - core::panicking::panic_fmt::h452a83e54ecd764e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
  16:     0x5749bc81b5a3 - core::panicking::panic::h440670b29ba8362f
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:127:5
  17:     0x5749bd66a1ca - bdk::types::FeeRate::from_btc_per_kvb::h0b4bc308299dd362
  18:     0x5749bced2263 - <swap::bitcoin::wallet::Client as swap::bitcoin::wallet::EstimateFeeRate>::estimate_feerate::hd7f9e08502ba7e4b
  19:     0x5749bc8cdb91 - swap::bitcoin::wallet::Wallet<D,C>::max_giveable::{{closure}}::h7e3c1cb85c2b2142
  20:     0x5749bc8c2ce4 - swap::api::request::Request::handle_cmd::{{closure}}::{{closure}}::{{closure}}::h337031554aba9fd5
  21:     0x5749bc8f2218 - <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::ha65d4d4953d67c5a
  22:     0x5749bc88d2c2 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h003e64477cc09207
  23:     0x5749bcb4dabc - swap::api::PendingTaskList::spawn::{{closure}}::{{closure}}::h87a16d7efb733e71
  24:     0x5749bcb37219 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h52edf6156be07a20
  25:     0x5749bcb59eaa - tokio::runtime::task::raw::poll::h6274c303559c96e2
  26:     0x5749bda53fd3 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h9318e936fe579030
  27:     0x5749bda53358 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hecb0df1ee0a10cc3
  28:     0x5749bda28dcd - tokio::runtime::context::set_scheduler::h9b638359b16372bc
  29:     0x5749bda3f74f - tokio::runtime::context::runtime::enter_runtime::h44c43aea703f0eba
  30:     0x5749bda52808 - tokio::runtime::scheduler::multi_thread::worker::run::hb848b575b7871a0a
  31:     0x5749bda3338a - tokio::runtime::task::core::Core<T,S>::poll::hc64d1b56b9c43239
  32:     0x5749bda25b1e - tokio::runtime::task::harness::Harness<T,S>::poll::he5fd2ccd53b7438a
  33:     0x5749bda4ba6d - tokio::runtime::blocking::pool::Inner::run::hd0d5a40beed4f367
  34:     0x5749bda50215 - std::sys_common::backtrace::__rust_begin_short_backtrace::h84e5530bb59e85bc
  35:     0x5749bda31099 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he69e213795392d71
  36:     0x5749bdb40c05 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h51435299acd7166e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
  37:     0x5749bdb40c05 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3f833c0a4926bdd4
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
  38:     0x5749bdb40c05 - std::sys::unix::thread::Thread::new::thread_start::h2c486d0230ab0d99
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/unix/thread.rs:108:17
  39:     0x777f87494ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  40:     0x777f87526850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  41:                0x0 - <unknown>
Error: task 25 panicked

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   1: swap::main::{{closure}}
   2: tokio::runtime::park::CachedParkThread::block_on
   3: tokio::runtime::context::runtime::enter_runtime
   4: swap::main
   5: std::sys_common::backtrace::__rust_begin_short_backtrace
   6: std::rt::lang_start::{{closure}}
   7: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:284:13
   8: std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
   9: std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  10: std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  11: std::rt::lang_start_internal::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:148:48
  12: std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  13: std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  14: std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  15: std::rt::lang_start_internal
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:148:20
  16: main
  17: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  18: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  19: _start
```
## asb POV
```2024-06-27T00:59:44.876594168Z DEBUG New connection established peer=12D3KooWHK6tsY16VorMPHnEgMvA9dUA6qPZQ9cqW5Hy5fZ3zNwL address=/ip4/192.168.122.27/tcp/43256
2024-06-27T00:59:44.877687674Z DEBUG ask_price=0.002698 BTC xmr=10.000000000000 XMR max_bitcoin_for_monero=0.02697995 BTC
2024-06-27T00:59:44.971358895Z DEBUG Lost connection to peer: Connection error: I/O error: connection is closed peer=12D3KooWHK6tsY16VorMPHnEgMvA9dUA6qPZQ9cqW5Hy5fZ3zNwL address=/ip4/192.168.122.27/tcp/43256
```
**Platform (please complete the following information):**

- CLI
- 0.13.1
- Ubuntu

**Comment by BrandyJSon** [comment]
Solution was specifying when called, sorry for posting the issue
--bitcoin-target-block #
